import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { useQuery, gql } from '@apollo/client';

const GET_USERS = gql`
  {
    users {
      id
      name
      email
      phone
      age
    }
  }
`;

export default function Home() {
  const { loading, error, data } = useQuery(GET_USERS);
  if (loading) {
    return <h1>Loading...</h1>;
  }
  if (error) {
    return <h1>Error!</h1>;
  }
  console.log(data.users);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div style={{ display: 'flex', flexWrap: 'wrap' }}>
          {data.users.map((user) => (
            <div
              style={{
                border: '1px solid #888',
                padding: '1rem 2rem',
                margin: '1rem',
              }}
              key={user.id}
            >
              <strong># {user.id}</strong>
              <h2>{user.name}</h2>
              <hr />
              <h4>Email: {user.email}</h4>
              <h4>Phone: {user.phone}</h4>
              <h4>Age: {user.age}</h4>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
